name: Build rootfs.tar.gz

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
        - edition: openrc
          extra_pkgs: openrc elogind-openrc
        - edition: runit
          extra_pkgs: runit elogind-runit
        - edition: s6
          extra_pkgs: s6-base elogind-s6
        - edition: suite66
          extra_pkgs: suite66-base elogind-suite66

    env:
      EDITION: ${{ matrix.edition }}
      EXTRA_PKGS: ${{ matrix.extra_pkgs }}

    steps:
      - uses: actions/checkout@v2
      - run: sudo -E ./build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: Artix-${{ matrix.edition }}
          path: build/Artix-${{ matrix.edition }}.zip
        if: github.ref == 'refs/heads/master'
